// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX-QYnaKGAjyiNjd9GkmNrHuQEYk7bkzg',
    appId: '1:1089320994377:web:7f8e95f616bc25e92d6198',
    messagingSenderId: '1089320994377',
    projectId: 'uoscaf-fb',
    authDomain: 'uoscaf-fb.firebaseapp.com',
    storageBucket: 'uoscaf-fb.appspot.com',
    measurementId: 'G-B9KGRW079K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDomsq8LY6UoT1Qdb2o6GIK6awjPgua_ZI',
    appId: '1:1089320994377:android:49486f4af0f2b4a02d6198',
    messagingSenderId: '1089320994377',
    projectId: 'uoscaf-fb',
    storageBucket: 'uoscaf-fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtdzrVKD-0a5cSskmQOTHHeydEVwUc3ew',
    appId: '1:1089320994377:ios:dc6e61844c7da0cd2d6198',
    messagingSenderId: '1089320994377',
    projectId: 'uoscaf-fb',
    storageBucket: 'uoscaf-fb.appspot.com',
    iosBundleId: 'com.example.uoscaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtdzrVKD-0a5cSskmQOTHHeydEVwUc3ew',
    appId: '1:1089320994377:ios:39ab1c4e3e18fd102d6198',
    messagingSenderId: '1089320994377',
    projectId: 'uoscaf-fb',
    storageBucket: 'uoscaf-fb.appspot.com',
    iosBundleId: 'com.example.uoscaf.RunnerTests',
  );
}
